name: Check Markdown

on:
  pull_request:

permissions:
  packages: read

jobs:
  lint-markdown:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@paritytech"

      - name: Install tooling
        run: |
            npm install markdownlint --save-dev
            markdownlint --version

      - name: Check Markdown
        env:
          CONFIG: .github/.markdownlint.yaml
        run: |
          markdownlint --config "$CONFIG" --ignore target .
